AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdademo.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaRest
      Description: 'Lambda function for CD Execution test'
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::015320530739:role/cc-lambda-pipeline'
      Policies:
        - AmazonDynamoDBFullAccess
      Environment:
        Variables:
          TableName: !Ref vehicleModel  
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get

      # Policies:

        # - Version: '2012-10-17'
        #   Statement:
        #     - Effect: Allow
        #       Action:
        #         - 'dynamodb:DeleteItem'
        #         - 'dynamodb:GetItem'
        #         - 'dynamodb:PutItem'
        #         - 'dynamodb:UpdateItem'
        #       Resource:
        #         'Fn::Join':
        #           - ''
        #           - - 'arn:aws:dynamodb:'
        #             - Ref: 'AWS::Region'
        #             - ':'
        #             - Ref: 'AWS::AccountId'
        #             - ':table/vehicleModel'
  vehicleModel:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: vehicleModel
      AttributeDefinitions:
        - AttributeName: model_id
          AttributeType: S
      KeySchema:
        - AttributeName: model_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
      