AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  carLambdaModel:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda-model.lambda_handler
      Runtime: python3.6
      CodeUri: ./car-model
      Description: 'Lambda function for to GET POST car model'
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::015320530739:role/cc-lambda-pipeline'
      Events:
        searchModelAPI:
          Type: Api
          Properties:
            Path: /model
            Method: GET
        putModelAPI:
          Type: Api
          Properties:
            Path: /model
            Method: POST
  carLambdaPrice:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambda-price.lambda_handler
      Runtime: python3.6
      CodeUri: ./car-price
      Description: 'Lambda function for GET POST car Price'
      MemorySize: 512
      Timeout: 30
      Role: 'arn:aws:iam::015320530739:role/cc-lambda-pipeline'
      Events:
        searchModelAPI:
          Type: Api
          Properties:
            Path: /price
            Method: GET
        putModelAPI:
          Type: Api
          Properties:
            Path: /price
            Method: POST
  model:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: model
      AttributeDefinitions:
        - AttributeName: model_id
          AttributeType: S
      KeySchema:
        - AttributeName: model_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5 
  price:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: price
      AttributeDefinitions:
        - AttributeName: price_id
          AttributeType: S
      KeySchema:
        - AttributeName: price_id
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5    