AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: CD Demo Lambda
Resources:
  CDDemoLambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: lambdademo.lambda_handler
      Runtime: python3.6
      CodeUri: ./LambdaRest
      Description: 'Lambda function for CD Execution test'
      MemorySize: 128
      Timeout: 30
      Role: 'arn:aws:iam::015320530739:role/cc-lambda-pipeline'
      Events:
        getAZsAPI:
          Type: Api
          Properties:
            Path: /getazs
            Method: get